---
title: "Market entry and house prices"
author: "Edu Gonzalo Almorox"
date: "27/10/2016"
setspace: doublespacing
output: word_document
bibliography: ex.bib

---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Introduction 

UK has experienced the fastest growth in house prices than any other OECD country during the last decades. Yet high prices in houses are a social problem due to “house affordability crisis” [@hilber2016]. One of the main results derived from this is the reduction of the homeowners. Businesses can also be affected by this inflationary trend. High house prices may suppose an important barrier that can prevent businesses to entry in a particular market. Hence, businesses that typically work with low margins, such as care homes, can be severely affected. If house prices in an area are high, care homes may no have the incentive to provide their long term care services there. As a result, people living in these areas may be foreclosed or at least find few social care options closer to them. 

The main question would be to test whether entries in the market are affected by the prices in the house market. If so, to what extent high house prices prevent the market entry? How other variables such as the quality ratings. 

The effects of house prices have been researched on a variety of contexts mostly analysing the decisions taken by households.  Yet, the ways firms may consider house prices in their decisions have received less attention and specially how these influence on their decision of entering in a local market. Care homes constitutes an important sector for analysis given the increasing necessity of social care for aged populations. 

## Institutional background 

Both planning and long term care are activities regulated by local authorities in Britain. The structure of those is nonetheless complex and entails organisation at different level - e.g. district or county depending on the type of services. 

### Long term care 

Long term care services may include both activities of daily living and health care. Currently there are 152 local authorities that rule the management - i.e. the provision and funding of these services. These 152 local authorities were established as a result of the Health and Social Care Act of 2012 and replaced the public health responsibilities of the former Primary Care Trusts.^[The activities associated with health issue were assigned to the Clinical Commissioning Groups (CCG). Currently there are 93 in England.] 

Long term services are provided by private providers. These are heterogenous and present different structures. 

## Planning regulations in England

The planning rules in England are now contained in the National Plannning Policy Framework (NPPF). Published in March 2012, the core purpose of this new regulatory framework consists of giving a greater role to local government in configuration of planning policies. The measures are intended to offer the appropriate incentives to local governments to enhance development.^[@hilber2015 argues the lack of local incentives to promote development. Whereas the main costs asssociated with development are mainly borne by local councils whereas the main fiscal profits remain collected by national authorities.]

## Hypothesis testing 

There are two potential mechanisms where house prices may influence the decision of a care homes to establish in a particular district. First, high prices may imply a fixed cost that may prevent care homes of joining a particular local market. On the other hand, the second mechanism may be based on wealth of the homeowners. In order to face possible financial pressures and given the cross-subsidation of publicly funded clients by self-funded, it seems plausible that care homes intend to locate in more affluent areas where there is likely higher proportion of self-fundeds. It is actually in these areas where the market shows more robustness. 


## Data

The anala ysis of these question entails the use of various data sources. The Care Quality Commission (CQC) directory of active and inactive care homes enables the calculation of entry rates. One of the main advantages of this dataset for the purposes of this research is that it allows for tracking the entries and exits of the care homes in the market. Concretely,  it reveals the date when the care homes are registered as well as deregistered in the CQC^[Since october 2010 the registration in the CQC is a legal requirement that every care has to meet in order to carry out a regulated long term care activity.] Besides, it provides a number of variables of interest such as the number of beds in the care home, the address, the local authority responsible for their activities and the provider group where the care belongs to. This dataset can be expanded with data from Laing Buisson. This is a commercial dataset that offers additional information that includes characteristics of the care home such as the primary client of the care homes (learning disability, dementia, old age, physical impairment), the type of care home (private – for profit, voluntary, public), whether it was purposely built and the number and type of rooms that it has. An important variable that complements the data available in the CQC registry is the date of first registration in the former regulator – the Commission for Social Care Inspection. This can help to determine two main issues, whether the care home was already in the market and for how long. The way to link both sources of information would be throughout the postal codes, the name of the care home, the location ID, the provider group and the region. 

The information corresponding prices of the properties would come from the price paid dataset released on a monthly basis by the Land Registry. This dataset contains all the transactions carried out in England and Wales since 1995. In addition to the price the paid for the transaction, the dataset includes further information such as the type of property, the address, whether it is newly built and whether the property is under leasehold or freehold.

To address the potential problems referred to the endogeneity associated with the house prices the identification strategy can be based on two common instruments used in the literature: variables that indicate some sort of elasticity in the supply of care homes [@saiz2010][@gyourko2008] and applied by [@hilber2016] for a UK context.

## Empirical model

The model of aims to capture the effects of the house prices on the care homes entry in the market. For doing that it exploits the variation of the house prices on different local authorities over time. The regressions could adopt a general specification such as: 

$E_{it} = \beta X_{it} + \alpha log(prices)_{it} + \theta_{it}$

Where $E$ represents the entry rate in a geographical unit (e.g.LSOA or MSOA) in a local authority  during a time period $t$ represents a set of observable controls that include the proportion of Job Seekers claimants, the proportion of old people, the proportion of people claiming for carers allowance, the Index of Multiple Deprivation, measures of market concentration (HHI, number of care homes within a certain distance, etc...). and are fixed effect that capture unobservable characteristics of the local authority and geographical unit respectively.  

### Bias and identification 

There are several elements of concern regarding potential bias. House prices are likely to be correlated with the amenities of the areas where they are settled. Since these are normally constant over time, it is possible to capture them throughout fixed effects. Also there may variables that affect simultaneously both house prices and market entries. An example of this may be a positive economic shock that incentivises entry in the market as well as increases the house prices. To deal with this type of omitted variable bias the literature has proposed various approaches on the basis of instrumental variables.

A first group of instruments has been associated with the housing supply elasticity. These have been based on the regulations of certain planning authorities. Hence, a measure of the degree of housing supply elasticity could be the refusal of big ‘major’ residential projects. This variable has been used recently in a UK context by [@hilber2016].  A second type of instruments that has been proposed consists of the variation of house ownership in a certain LSOA. The underlying idea behind it changes in prices will induce different wealth effects given the proportion of owners and renters in a certain area.

The second strand of research questions consists of the analysis of potential effects associated with the entry of care homes.

## Results




## References 


