---
title: "Market entry in the care homes market"
author: "Edu Gonzalo Almorox"
date: "null"
output: word_document

---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Disclaimer

This is an early version of the document: COMMIT TO HAVE A CONTROL VERSION DO NOT PUSH TO GITHUB!


## 1. Introduction

## 2. Institutional context: the market for care homes 

## 3. Data and Variables 


To conduct our empirical analysis we use data from different sources. Prior to discuss the different datasets that we combine, we begin this section by describing how we the entries and how we build the variables of to capture them. Since the calculation of entry rates involves the number of incumbent companies in a certain market, we also calculate the entries.

### 3.1 Entry rates

We use data from the registry of active and inactive care homes in the Care Quality Commission for calculating the entry rates -_This dataset can be accessed upon request to Care._ - This dataset essentially captures the information regarding the registration of care homes and nursing homes in the Care Quality Commission. Since 2010, registration in the CQC is a legal requirement 
 that every provider must meet before running a regulated activity of long term care. The dataset for the analysis covers then registrations from 2010 until September 2016. 
 
In our sample, our unit of analysis are care homes that registered and/or unregistered. We can identify them by means of two main variables: a numeric 
 identification code and the name of the location. Since names are likely to 
 contain typographical errors we use the numeric identificator to characterize the 
care homes. Our initial sample contains 23,775 care homes located in over 17,800 post codes. Therefore, various care homes may be addressed to the same postcode. This issue has several implications for our purposes. In this case, care homes are registered as a result of the formal requirement. However, it may happen that the care home is subject to a legal change such as the a change in the regulated activity or in the provider. I differentiate between this two types of entries: _the novo_ and _spurious_ as a result of a change in the formal figure. 

Data from the Care Quality Commission are extended with data from Laing and Buisson. This is commercial dataset that offers alternative information to what can be found from the CQC registry. For our purposes, we retrieve information about the first registry date of the care home and whether the care home was built on purpose or was registered under other circumstances. 

For matching both datasets we first use the postcode as the key variable. Postcodes are associated to various names of care homes as well as IDs. For the second step we create a key variable based on the name of the locations in order to remove duplicate observations.

I select only observations that correspond to residental care homes

## Empirical model  

### Identification strategy

## Results 

## Discussion

## Conclusion

## Appendix

### Laing and Buisson data 

Data available correspond to years 2012, 2013 and 2014. Each sample contains the following number of observations (...). In some cases, the information corresponding to each observation presents some inconsistencies. Particularly, some care homes present various types of primary clients accross the years as well as different denominations. 

A close exploration of the Laing Buisson data lets us know that some care homes had different types of clients and alos had different denominations. For dealing with these problems we have created a variables that capture these issues. 
